version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # This will allow live reloading during development
    environment:
      MONGO_URL: mongodb://mongo:27017  # Use the internal MongoDB URL for service communication
    # If you want to use your existing connection string, uncomment the line below:
    # - MONGO_URL=mongodb+srv://wajed:lTOT32yLyrp7Zev0@cluster0.frdac.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
